#!/usr/bin/env bash
set -euo pipefail

PS3="Choose a language: "
select LANGUAGE in java python ruby; do
  case $LANGUAGE in
    java|python|ruby) break ;;
    *) echo "Please enter 1 or 2." ;;
  esac
done

echo "NEXT_PUBLIC_CODE_LANGUAGE=$LANGUAGE" > .env.local
npm run dev
